/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"//"“引入自己的头文件<>引入系统
/* Header for class com_tck_NdkSimple */

//用来打一个标记 c在编译的时候会把头文件copy到引入的地方
//不管是重复引用还是相互引用，都只会copy一次
#ifndef _Included_com_tck_NdkSimple
#define _Included_com_tck_NdkSimple
#ifdef __cplusplus//相当于if语句c++
// c里面不允许函数重载 c++里面可以
//不管是c还是c++同一采用c的编译方式
extern "C" {
#endif
/*
 * Class:     com_tck_NdkSimple
 * Method:    getSingnaturePassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tck_NdkSimple_getSingnaturePassword
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
