/* DO NOT EDIT THIS FILE - it is machine generated */
#include "jni.h"//"“引入自己的头文件<>引入系统
/* Header for class com_tck_NdkSimple */

#ifndef _Included_com_tck_NdkSimple
#define _Included_com_tck_NdkSimple
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_tck_NdkSimple
 * Method:    getSingnaturePassword
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_tck_NdkSimple_getSingnaturePassword
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
